import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../main.dart';

Lang strings = Lang();

class Lang {

  var direction = TextDirection.ltr;
  var locale = "en";

  Map<int, String> langEng = {
    0 : "HANDYMAN",
    1 : "SIGN IN",
    2 : "Enter your Phone number",
    3 : "Enter your Password",
    4 : "Enter your Email",
    5 : "Remember me",
    6 : "Forgot password?",
    7 : "I agree with",
    8 : "Terms & Conditions",
    9 : "Sign Up",
    10 : "Sign In",
    11 : "or continue with",
    12 : "Please Enter Email",
    13 : "Please Enter Password",
    14 : "SIGN UP",
    15 : "Confirm Password",
    16 : "Enter your Name",
    17 : "Next",
    18 : "Please enter Your registered email so that we can help you to recover Your password.",
    19 : "Home",
    20 : "Favorites",
    21 : "Cart",
    22 : "Notify",
    23 : "Menu",
    24 : "Search",
    25 : "Categories",
    26 : "View all",
    27 : "Top Rating",
    28 : "Top Trends",
    29 : "Providers",
    30 : "Not available Now",
    31 : "Service",
    32 : "Provider",
    33 : "Search in favorites",
    34 : "Filter",
    35 : "Apply Filter",
    36 : "Reset Filter",
    37 : "Sort by",
    38 : "Ascending (A-Z)",
    39 : "Descending (Z-A)",
    40 : "Filter by",
    41 : "Currently available services",
    42 : "Discounted services",
    43 : "Price",
    44 : "Rating",
    45 : "Profile",
    46 : "Privacy Policy",
    47 : "About Us",
    48 : "Dark Mode",
    49 : "My Address",
    50 : "Language",
    51 : "Sign Out",
    52 : "Select Language",
    53 : "SUBMIT",
    54 : "Please Enter Email",
    55 : "Please enter password",
    56 : "Passwords are not equal",
    57 : "Email are wrong",
    58 : "Set Location",
    59 : "Find services near your",
    60 : "By allowing location access, you can search for services and providers near your.",
    61 : "Use currents location",
    62 : "Set from map",
    63 : "Pick the Address",
    64 : "This address",
    65 : "Please enter address",
    66 : "Add the location",
    67 : "Label as",
    68 : "Home",
    69 : "Office",
    70 : "Other",
    71 : "Delivery Address",
    72 : "Contact name",
    73 : "Contact phone number",
    74 : "Save location",
    75 : "Enter Delivery Address",
    76 : "Enter Contact phone number",
    77 : "Enter Contact name",
    78 : "My Address",
    79 : "Address not found",
    80 : "Add address",
    81 : "Location",
    82 : "Booking",
    83 : "Services not found",
    84 : "Providers not found",
    85 : "You are not authorized",
    86 : "Not found ...",
    87 : "Notifications",
    88 : "Today",
    89 : "Running",
    90 : "History",
    91 : "My Booking",
    92 : "Quantity",
    93 : "Addons",
    94 : "Add to cart",
    95 : "Total amount",
    96 : "Monday",
    97 : "Tuesday",
    98 : "Wednesday",
    99 : "Thursday",
    100 : "Friday",
    101 : "Saturday",
    102 : "Sunday",
    103 : "Weekend",
    104 : "Galleries",
    105 : "Reviews & Ratings",
    106 : "My Profile",
    107 : "Everything about you",
    108 : "Name",
    109 : "Enter your name",
    110 : "Email",
    111 : "main@gmail.com",
    112 : "Phone number",
    113 : "9091234566789",
    114 : "SAVE",
    115 : "Change password",
    116 : "New password",
    117 : "123456",
    118 : "Confirm New password",
    119 : "CHANGE PASSWORD",
    120 : "Enter Password",
    121 : "Enter Confirm Password",
    122 : "Passwords are not equal",
    123 : "Please Enter name",
    124 : "Change profile",
    125 : "Change avatar",
    126 : "From Library",
    127 : "From Camera",
    128 : "Total booking",
    129 : "Total spent",
    130 : "Get favorite service",
    131 : "Select your location to see the wide range providers and booking your desired service.",
    132 : "Easy payment",
    133 : "Booking service with COD payment or pay by safer and faster payment gateways.",
    134 : "Fast work",
    135 : "Hundreds of service man are waiting for you booking.",
    136 : "Skip",
    137 : "GET STARTED",
    138 : "Chat",
    139 : "Write your message ...",
    140 : "Pending",
    141 : "Track booking",
    142 : "Booking tracking",
    143 : "Booking not found",
    144 : "Booking details",
    145 : "Order ID:",
    146 : "Payment",
    147 : "Cash payment",
    148 : "Status",
    149 : "Accept",
    150 : "Addons:",
    151 : "Quantity:",
    152 : "Item price",
    153 : "Subtotal",
    154 : "Discount",
    155 : "VAT/TAX",
    156 : "Total amount",
    157 : "Cancel booking",
    158 : "My Cart",
    159 : "Category",
    160 : "Your cart in empty",
    161 : "Proceed to checkout",
    162 : "Checkout",
    163 : "Confirm order",
    164 : "CODE123",
    165 : "Apply",
    166 : "Choose payment method",
    167 : "Pay your payment after getting service",
    168 : "Digital payment",
    169 : "Faster and safer way to send money",
    170 : "Additional note",
    171 : "Back to Home",
    172 : "You Place to Booking Successfully",
    173 : "Your Booking is placed successfully. We start our work process and you will receive your service soon.",
    174 : "Select Address",
    175 : "Reset password email sent. Please check your mail.",
    176 : "Please enter phone",
    177 : "User not found",
    178 : "User is disabled. Connect to Administrator for more information.",
    179 : "Code sent. Please check your phone for the verification code.",
    180 : "Time Out",
    181 : "Please enter valid code",
    182 : "User don't create",
    183 : "Chat message",
    184 : "From user:",
    185 : "New Booking was arrived",
    186 : "Now status:",
    187 : "Booking status was changed",
    188 : "Coupon not found",
    189 : "Coupon has expired",
    190 : "Coupon not supported by this provider",
    191 : "Coupon not support this category",
    192 : "Coupon not support this service",
    193 : "Coupon activated",
    194 : "Description",
    195 : "Enter your Phone number. We'll sent verification code.",
    196 : "Phone verification",
    197 : "We've sent 6 digit verification code.",
    198 : "Please enter code",
    199 : "Your phone number verified. You can't edit phone number",
    200 : "Data saved",
    201 : "Password changed",
    202 : "Current address",
    203 : "Latitude",
    204 : "Longitude",
    205 : "Please select address",
    206 : "Service added to cart",
    207 : "fixed",
    208 : "hourly",
    209 : "ratings",
    210 : "This service already in the cart",
    211 : "Proceed all checkout",
    212 : "Coupon Code",
    213 : "Requested Service on",
    214 : "Any Time",
    215 : "Schedule an Order",
    216 : "Select a Date & Time",
    217 : "CONTINUE",
    218 : "Booking ID",
    219 : "Your address is outside provider work area",
    220 : "See details",
    221 : "Provider Location",
    222 : "Show only service with",
    223 : "stars",
    224 : "Show any stars",
    225 : "Nearby you",
    226 : "Far",
    227 : "Are you sure you want to exit?",
    228 : "No",
    229 : "Exit",
    230 : "Near by",
    231 : "Services nearby",
    232 : "Open Provider Page",
    233 : "Subcategory",
    234 : "Share App",
    235 : "Share This App",
    236 : "Enable Notify",
    237 : "Comment",
    238 : "Address",
    239 : "Appointed time",
    240 : "Call now",
    241 : "Message",
    242 : "Rate this provider",
    243 : "Wait for a response from the provider",
    244 : "Leave a Review",
    245 : "Click on the stars to rate this service",
    246 : "Tell us something about this service",
    247 : "Add Images",
    248 : "From Gallery",
    249 : "From Camera",
    250 : "Submit Review",
    251 : "Please enter text",
    252 : "Blog",
    253 : "Loading ...",
    254 : "Other addresses",
    255 : "Write your review",
    256 : "Administrator",
    257 : "Related products",
    258 : "See more",
    259 : "Products",
    260 : "in stock",
    261 : "Please select variant",
    262 : "Product added to cart",
    263 : "This product already in the cart",
    264 : "Provider products",
    265 : "Other products",
    266 : "Find what you need",
    267 : "Sort by provider",
    268 : "Not select",
    269 : "Chat with provider",
    270 : "Minimum purchase amount for this provider: ",
    271 : "Maximum purchase amount for this provider: ",
    272 : "Pay with",
    273 : "Provider can't enter to customer app. Please use another credentials.",
    274 : "Remove",
    275 : "Promo code",
    276 : "Add promo",
    277 : "Promo not found",
    278 : "Apply code",
    279 : "Your promo code",
    280 : "Enter code",
    281 : "Coupon not support this product",
    282 : "My rewards",
    283 : "Special offer",
    284 : "Use now",
    285 : "Valid until",

  };

  Map<String, dynamic>? defaultLang;

  setLang(Map<String, dynamic> _def, String _locale, BuildContext context, TextDirection _direction){
    defaultLang = _def;
    locale = _locale;
    direction = _direction;
    Provider.of<LanguageChangeNotifierProvider>(context,listen:false).changeLocale(locale);
  }

  String get(int id){
    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    }else{
      if (defaultLang![id.toString()] != null)
        return defaultLang![id.toString()];
      return langEng[id] == null ? "" : langEng[id]!;
    }
  }
}
